### ISSUE TITLE
Event listener tags

### ISSUE THREAD

**Issue by czyzby** [czyzby/gdx-lml#13]
There are several cases where you might want to add some actors to the stage after a delay, when certain condition is met (for example: a button is clicked). For now, you can solve it by attaching a standard listener, which invokes a Java method that loads another template - for example, the one containing dialog data. However, it would be really useful if you could solve this issue entirely with LML code:
```
<button>
  <onClick>
    <dialog> ... </dialog>
  </onClick>
</button>
```
In the example above, a `Dialog` instance would be shown on the screen when the `Button` is clicked, rather than immediately added to the stage.

Such tags could be added in two ways:

- macros: data between their tags would be stored as simple string and parsed as soon as the event occurs to show the requested actors. This would require to parse the template multiple times (unless cache mechanism is added) for each event. The templates would be in a separate context: any arguments from the original file would not be accessible.
- tags: a special group tag would have to be added. Actors would be parsed immediately along with the rest of the template and added to the specialized group, only to be stored until the event occurs. This would allow to create actors within the same context and keep local "variables" (`{arguments}`). Actors would be created unnecessarily if the event never occurs though, so macro solution would still be preferred if the event is expected to occur rarely.

I think both ways would have their uses and both should be available. `ClickListener` and `ChangeListener` are obvious choices, not sure if any other listeners should be added.

**Comment by czyzby** [comment]
> I have a LmlView created with #createView.
> If I want to display a dialog that would get called by my Java code (for example to display a warning).
> For this I would have a custom <:macro alias="warning dialog"> or a simple template with the dialog (need your suggestion here).
> 
> And then, when my java code wants to display the dialog, it would call LmlParser#fillStage("dialogtemplate.lml", LmlView$getStage())?
> 
> In this case, it's better to have a dedicated template than a custom macro right?

@jpsgamboa, now the default way of handling such situation is using a listener tag or macro: `onClick`, `onChange`, `:onClick` or `:onChange`. `gdx-lml-tests` and `gdx-lml-vis-tests` projects are already updated with example uses of all 4 of these tags.

**Comment by jpsgamboa** [comment]
Thanks! May I ask you for an example of how would you implement a generic dialog with "yes" or "no" buttons that could be called from an event like this via LML or directly from Java code? 

The example you provided above would serve as generic "warning" dialog, but what if I wanted a generic structure with 2 buttons? How could I handle the click event on those buttons for differently in different contexts?

Sorry if I'm repeating questions.

**Comment by czyzby** [comment]
```
<:macro alias="showChoice" replace="content" title="@choice" onYes="close" onNo="close">
  <onChange>
    <dialog title="{title}">
      {content}
      <textButton onResult="{onYes}">@yes</textButton>
      <textButton onResult="{onNo}">@no</textButton>
    </dialog>
  </onChange>
</:macro>
```
```
<!-- Closes on no, invokes myAction on yes: -->
<:showChoice onYes="myAction">
  Do you really want to do it?
</:showChoice>
```

**Comment by jpsgamboa** [comment]
I have a doubt regarding the `button` attribute of the `:clicklistener ` macro. The java class says it attaches the `clicklistener ` the button ID I choose, but why is this an option if the `<:clicklistener>` will already be inside the `<button>` tag like this:
```
<textbutton>
    Click me.
    <:clicklistener>
        <:doSomething></:doSomething>
    <:clicklistener>
</textbutton>
```
Or the idea is to be able to do this?:

```
<:clicklistener button="button1">
    <:doSomething></:doSomething>
<:clicklistener>

<textbutton id="button1">
    Click me.
</textbutton>
```

**Comment by jpsgamboa** [comment]
Getting a `NullPointerException` in the following scenario:
Main View:
```
<table id="appRootTable" fillparent="true" align="top" debug="true">
    <:import path="templates/menubar.lml"/>
</table>
```
The imported `menubal.lml` (haven't gotten around to replace `import` with a macro as you suggested yet):

```
<menubar id="menuBar" growx="true" align="top" row="true">
    <menu text="@ui.file">
        <menuitem>@ui.new</menuitem>
        <menuitem onclick="file-open">@ui.open</menuitem>

        <menuitem>@ui.openRecent
            <submenu>
                <menuitem>@ui.comingSoon
                    <:onclick cache="true">
                        <:showPosNegDialog title="my title">
                            Are you sure?
                        </:showPosNegDialog>
                    </:onclick>
                </menuitem>
            </submenu>
        </menuitem>

</menubar>
```
Finally, the global macro:
```
<:macro alias="showPosNegDialog" replace="content" title onPositive="close" onNegative="close" positiveText="Yes" negativeText="No">
<dialog title="{title}" defaultpad="4">
    {content}
    <textbutton onresult="{onPositive}">{positiveText}</textbutton>
    <textbutton onresult="{onNegative}">{negativeText}</textbutton>
</dialog>
</:macro>
```
The error is not much helpful, but it looks like when `AbstractListenerLmlMacroTag.addActors` calls `actor.getStage()` the stage is `null`, .

The error occurs when I click the button with the listener. The `Actor` is not `null` though, but his `stage `and `parent `are.

Full error:
```
java.lang.NullPointerException
	at com.github.czyzby.lml.util.LmlUtilities.appendActorsToStage(LmlUtilities.java:215)
	at com.github.czyzby.lml.parser.impl.tag.macro.AbstractListenerLmlMacroTag.addActors(AbstractListenerLmlMacroTag.java:84)
	at com.github.czyzby.lml.parser.impl.tag.macro.AbstractListenerLmlMacroTag.doOnEvent(AbstractListenerLmlMacroTag.java:77)
	at com.github.czyzby.lml.parser.impl.tag.macro.ClickListenerLmlMacroTag$1.clicked(ClickListenerLmlMacroTag.java:54)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:81)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Input.update(Lwjgl3Input.java:187)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:237)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:122)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:95)
```

**Comment by czyzby** [comment]
> Or the idea is to be able to do this?:

> ```
> <:clicklistener button="button1">
>     <:doSomething></:doSomething>
> <:clicklistener>
> 
> <textbutton id="button1">
>     Click me.
> </textbutton>
> ```
No. This the button ID from `ClickListener` API: see `ClickListener#setButton`.

**Comment by czyzby** [comment]
I'm afraid this is *not* an LML issue. `MenuItem` reports `null` stage, as if it wasn't shown in the first place. Try the following code:

```
<menuBar>
  <menu text="menu">
    <menuItem>submenu
      <subMenu>
        <menuItem onClick="print">item
        </menuItem>
      </subMenu>
    </menuItem>
  </menu>
</menuBar>
```

```
    @LmlAction("print")
    void print(final MenuItem item) {
        System.out.println(item.getStage());
    }
```

You'll notice that `null` is printed to the console each time. That's why click listener cannot add the actors to the stage - there is no stage to begin with. Although this cannot happen if the actor is implemented correctly, I'll add a meaningful error to `LmlUtilities`. I'm afraid @kotcrab has to fix it in **VisUI**.

See https://github.com/kotcrab/vis-editor/issues/160.

**Comment by czyzby** [comment]
Added LML workaround that extracts `Stage` from ancestors of the tag if no `Stage` is found on the actor with the listener attached. Your code should work now.

**Comment by czyzby** [comment]
> Or the idea is to be able to do this?:
> ```
> <:clicklistener button="button1">
>     <:doSomething></:doSomething>
> <:clicklistener>
> 
> <textbutton id="button1">
>     Click me.
> </textbutton>
> ```

Now that I think about, it would be pretty useful if you wanted to reuse the same listener multiple times in one template - maybe not your usual use case, but might still be useful. Especially since you can add conditionals. Consider this:
```
<textButton id="someValue">
  <onClick if="$isError" attachTo="someValue;anotherValue">
     <dialog title="@error">@someError<button onResult="close"/></dialog>
  </onClick>
</textButton>
<textButton id="otherValue"/>
<textButton id="anotherValue"/>
```
```
@LmlAction("isError")
boolean isInvalid(TextButton button) {
  String id = LmlUtilities.getActorId(button);
  // proceed with validation
  return result;
}
```
This would allow you to reuse the click listener, while still allowing you to have some actor-specific treatment thanks to Java implementation. Again - not your usual use case, but we should allow that.

**Comment by czyzby** [comment]
Listeners can be shared between multiple actors - or even views - thanks to the new `ids` and `keep` attributes. Snippet from the tests project:

> ```
> 
>  
>  <:onClick ids="clickA;clickB" cache="true">
>     <dialog style="dialog" title="$random">
>          Attached to multiple actors.
>          <textButton onResult="close">Great.</textButton>
>     </dialog>
>  </:onClick>
>  <textButton id="clickA">Same listener as next button.</textButton>
>  <textButton id="clickB">Same listener as previous button.</textButton>
> ```

**Comment by czyzby** [comment]
@jpsgamboa, I'd appreciate if you looked into the new input listener tags. Examples are already updated.

**Comment by jpsgamboa** [comment]
Sorry for the delay.
Can confirm the `AbstractLmlTag#determineStage` workaround is working! Nice one.

The new `ids` attribute is also working fine for me. I think this is a very nice addition. Feels intuitive and gives us a lot of freedom!

PS: It's funny how in just a few hours time frame that I don't read the updates here, your comment chain always goes from "maybe it would be nice to.." into "implemented it". You're a machine, man.

**Comment by czyzby** [comment]
Yeah, I want to finish up LML to be honest. Since `Scene2D` API is pretty much covered and LML is more or less clean, I don't think there are going to be any major changes from now on. That's why I want to implement the missing features and do some refactoring before releasing the next version.
