### ISSUE TITLE
Create alternative gdx-setup

### ISSUE THREAD

**Issue by czyzby** [czyzby/gdx-lml#20]
Since `Autumn MVC` is unlikely to make it to the third-party extensions and official `gdx-setup` does not support project templates (and isn't even written with LibGDX, which makes it awkward to extend), a separate setup tool would be nice. Especially since [Dragome backend](https://github.com/dragome/gdx-dragome) is being created and it should come with a proper setup tool.

General ideas:
- Written in Kotlin: multiline strings and string templates will allow to easily create stuff like Gradle build files directly in code, without a separate template mechanism.
- **Based on LibGDX**, ditches Swing and AWT. Isn't it ironic that a *graphical applications framework* uses *another* framework to create a *graphical application* that generates its projects?
- Easier to maintain: Gradle allows to use the latest available release with `+`. When creating a new project, you'll most likely want to use the new versions of libraries anyway - by using `+`, maintainers of third party libraries will not have to update `gdx-setup` each time they make a release.
- Support most features from the original gdx-setup.
- Do **not** force any specific Gradle release, or include Gradle wrappers (unless asked to). Installing Gradle globally on the machine is the sensible way to go, so wrappers should be optional.
- Include support for project templates. Instead of generating semi-empty project drawing BadLogic logo, you could use a template for `ApplicationListener`, `ApplicationAdapter`, `Game`, (LibGDX) `AbstractApplicationListener` (Kiwi), `LmlApplicationListener` (LML), `AutumnApplication` (Autumn MVC) or any other `ApplicationListener` implementation from external libraries. This should help setting up some more complex projects, especially for beginners, as they might lack their personal "template projects" that could be easily copied.
- Responsive validation. Use **VisUI** forms to validate user input.
- Internationalization. Use i18n bundles to make it possible to easily translate the tool.
- Support for different JVM languages. Allow to optionally include extra JVM languages (that are pretty popular) like Kotlin, Scala or Groovy.
- Use **VisUI** file chooser to add support for favorite directories. Remember basic preferences (last used package, etc.).
- Dependency version customization. Defaults to `+` (latest), every library should be customizable. Keep versions in `gradle.properties`.

**Comment by czyzby** [comment]
GUI prototype:
![gdx-setup](https://cloud.githubusercontent.com/assets/11707612/14667413/6d925c58-06df-11e6-820a-efa695768e4d.png)

**Comment by WimpyMistake** [comment]
That looks awesome! Can't wait to see more of it.

**Comment by czyzby** [comment]
I think a lot of newcomers have problems setting up additional projects, like server (additional application within the same Gradle project) and  shared (available for both client and server applications). While you're absolutely right - I *will* make it possible to use my web socket libraries - I'm also planning on adding template project using LibGDX sockets API.

**Comment by czyzby** [comment]
@kotcrab @WimpyMistake @jpsgamboa The new `gdx-setup` is currently able to generate simple projects LibGDX. Comparing to official application, these features are currently unsupported:

- *Android SDK analysis*: application does not validate if you gave it a correct path to the Android SDK, or if your selected target Android version is available.
- *Gradle wrapper* is not included. I might throw in optional Gradle wrapper generation.
- *Extensions validation*: you can select GWT-incompatible extensions and no warnings are shown. However, all descriptions mention if they do not support a specific problem, so this should not be an issue.
- *Success dialog*: currently there is no dialog shown after project generation, but I plan on including some tips how to import the project, run it, etc.

Additional features:
- You can choose different languages (like Scala, Kotlin, Groovy) - their Gradle plugins will be included and source folders generated in all projects.
- Templates: you can generate different basic sources, according to your needs. No more badlogic logo by default! (Sorry, guys.)
- Favorites: right-click on folders to add them to favorites.
- Much more settings - see advanced tab.

I'd love to hear suggestions about the GUI, possible new extensions and new templates. I'm already working on some more useful template projects, like LML and LML-Vis templates.

**Comment by WimpyMistake** [comment]
Great job!
I have tested it and created few projects. Love how it re-populate last created form values and the favourites directory.
Anyway, as per my first time experience, i believe it would be better if the setup output generation progress (maybe some text or progress bar). And like listed above, Success Dialog after generation finished.
As for templates, Autumn MVC off course and other gdx library that you have (kiwi, websocket etc). And if possible, provide templates that _do something_. Example, like the original official app, generated project does display badlogic logo. 
In term of UX, i feel that you should use different font colors to distinguish between info and error text. For example, "Project Name cannot be empty" stays as red while "See gdx-pay for cross platform in-app purchasing" to other color (white should be enough)

**Comment by czyzby** [comment]
> Anyway, as per my first time experience, i believe it would be better if the setup shows generation progress (maybe some text or progress bar).
It would go from 0 to 100% in a fraction of second, as it currently takes about a second to generate a new project, 99% of which is the dialog fading time. : P

However, I do plan on adding text area with Gradle logs once optional Gradle wrapper is included.

> In term of UX, i feel that you should use different font colors to distinguish between info and error text. 
You're right. Errors and links will stay red-ish, info messages will be white.

**Comment by czyzby** [comment]
Moved to https://github.com/czyzby/gdx-setup/

**Comment by czyzby** [comment]
`gdx-setup` branch was deleted. To check application's current status, see [the new, separate repository](https://github.com/czyzby/gdx-setup/).
