### ISSUE TITLE
Spinner doesn't fire change events on input

### ISSUE THREAD

**Issue by metaphore** [czyzby/gdx-lml#31]
I've spotted that unlike other input widgets, `Spinner` doesn't trigger `ChangeEvent` when you type anything in the field. `ChangeEvent` get fired only if one of the increment/decrement buttons has been pressed or user hit Enter.

There is no any ability to switch that behavior.

Simple fix could look like this (`IntSpinnerModel` for example):
```java
@Override
public void textChanged () {
	String text = spinner.getTextField().getText();
	if (text.equals("")) {
		current = min;
	} else if (checkInputBounds(text)) {
		current = Integer.parseInt(text);
        spinner.notifyValueChanged(true); // <--- here it is
	}
}
```

**Comment by czyzby** [comment]
AFAIK, `Spinner` is a widget from VisUI. LML approach is rather generic and there are no plans for special cases of listener attributes or fixes of Scene2D/VisUI. I'm pretty sure `ChangeListener` is added to `Spinner` actors as expected; if you want `Spinner` to work differently, you should add this issue to [VisUI](https://github.com/kotcrab/vis-editor/) repository.

**Comment by metaphore** [comment]
Oh, sorry, messed up with repo.
