### ISSUE TITLE
Image element missing image/drawable attribute

### ISSUE THREAD

**Issue by metaphore** [czyzby/gdx-lml#35]
It seems like there is no way to set `Drawable` for `Image` from LML markup.
I guess there should be *drawable* attribute that sets image from current skin.

**Comment by czyzby** [comment]
There is. The usual `style` attribute takes a `Drawable` instance from the skin in case of `Image` actors. See [`gdx-lml-tests`](https://github.com/czyzby/gdx-lml/blob/master/examples/gdx-lml-tests/core/assets/templates/examples/image.lml).

**Comment by metaphore** [comment]
Oh sure. Maybe it would be better to add some aliases to `style` attribute for `Image` to make it more explicit?

**Comment by czyzby** [comment]
LML is already flooded with too much meta-data at runtime - I think I actually removed such alias back when I was doing a major clean up. (Or maybe it was LML 0 -> 1 transition, not sure.) I think `style` attribute is consistent with other actors and should be clear enough. If you want such alias in your application, I can post a simple code snippet how to set it up.

The main reason why I don't want to add such alias is that it would apply to all actors that extend `Image`, including LML's `AnimatedImage` (which uses multiple drawables).

**Comment by metaphore** [comment]
Got it, thanks!
