### ISSUE TITLE
Add Spinner#TextFieldEventPolicy property as LML attribute

### ISSUE THREAD

**Issue by metaphore** [czyzby/gdx-lml#37]
Since VisUI 1.1.6 `Spinner` has `TextFieldEventPolicy` that can configure notification behavior

**Comment by metaphore** [comment]
Oh, just noticed that it's already covered in #28

**Comment by czyzby** [comment]
Yeah, I need to update some VisUI-related stuff. I haven't released `1.8` version yet because of this. However, I've been focusing on [KTX](https://github.com/czyzby/ktx) lately, so I'm not sure when I'll finally close #28.
