### ISSUE TITLE
websocket terminate connection if server not sending ping

### ISSUE THREAD

**Issue by Nikolay206** [czyzby/gdx-lml#39]
In this version, if the server has not sent packets, connection terminated.

connection terminated hear
```
class WebSocketInputStream 
{
...
void readBytes(byte[] buffer, int length) throws IOException, WebSocketException
    {
            ...       
            int count = read(buffer, total, length - total);
            if (count <= 0)
            {
                // The end of the stream has been reached unexpectedly.
                throw new WebSocketException(
                        WebSocketError.INSUFFICENT_DATA,
                        "The end of the stream has been reached unexpectedly.");
            }
            total += count;
        }
    }
}
```
It would be nice to have a boolean property terminateConnectionAfterTimeOut to control behavior 
if terminateConnectionAfterTimeOut == false then connection is not ternubated

**Comment by czyzby** [comment]
Looks like this is a code snippet from the `nv-websocket-client` library. If I'm understanding correctly, your client connection is closed if you do not send any packets for a while.

Well, I can only say that timeout on web sockets seems logical: setting an enormous timeout value or some workaround boolean is not a solution to your problem. I'd advise you to just send keep alive packets (basically, empty web socket packets) every once in a while to keep the connection going and prevent it from closing.

**Comment by Nikolay206** [comment]
As far as I know, TCP is not closed on timeout. 
Why do I need to send empty packets?

**Comment by czyzby** [comment]
`nv-websocket-client` has a timeout setting. If you want the client to use an infinite timeout value, you can modify [this property](https://github.com/TakahikoKawasaki/nv-websocket-client/blob/master/src/main/java/com/neovisionaries/ws/client/WebSocketFactory.java#L190) manually. I don't think this property is available on every platform (I'd probably include it in the `WebSocket` API), sorry. I'll look into it before next release.

**Comment by Nikolay206** [comment]
thank you very much. I try to use this parameter.
