### ISSUE TITLE
Autumn: Ability to remove event listeners from code

### ISSUE THREAD

**Issue by metaphore** [czyzby/gdx-lml#40]
In some point I want to get more control over `EventDispatcher`, just like subscribe and unsubscribe from particular events right from the code.

It's useful when I instantiate objects by myself and thus they can't have injected fields and all the tricks with annotated methods. So I have to do all of that by my own code. One of those cases is related to events, what if I just want to some particular class to manage its event subscription on its own (like if this is poolable object and has init/reset methods).

`EventDispatcher` has ability to add listeners manually, but there is no way to remove them (boolean return value inside event method doesn't count).

What do you think, is it possible to extend `EventDispatcher` in that way?

And one a bit of off-topic question. In such cases, when I have no options but to inject `Component` instances by own code, is there any sort of Autumn context that holds all references of singleton system components (like classes annotated with `Component` or `View`), so I can easily access those instances from any place in code?

**Comment by czyzby** [comment]
> And one a bit of off-topic question. In such cases, when I have no options but to inject `Component` instances by own code, is there any sort of Autumn context that holds all references of singleton system components (like classes annotated with `Component` or `View`), so I can easily access those instances from any place in code?

[Yes, there is.](https://github.com/czyzby/gdx-lml/blob/master/autumn/src/main/java/com/github/czyzby/autumn/context/Context.java#L104) `Context` instance is a component itself, so you can inject it anywhere.

**Comment by czyzby** [comment]
Sure, removal method seems only logical. I'm surprised I haven't added it already.

By the way, I'd like to spend some time on LML/Autumn this weekend (basically - close all current issues, release `1.8`), so if consider any other APIs questionable, don't hesitate to create new issues.

**Comment by czyzby** [comment]
On a side note: Autumn clears the context after full application initiation to limit unnecessary meta-data. Autumn's aim was basically to help you with your application setup thanks to some reflection magic - at the cost of a little bit longer start up time, but with little-to-none reflection usage at runtime. The reasoning was simple: `Context` should not be a global variable container equivalent. If you need some components - inject them on object creation. If you need to dynamically create objects at runtime through providers or factories: inject `DependencyProvider` for the selected type.

If you really need the constant access to the `Context`, [use this property](https://github.com/czyzby/gdx-lml/blob/master/autumn/src/main/java/com/github/czyzby/autumn/context/Context.java#L37). It will prevent the `Context` from being cleared. The overhead should not be noticeable though, so do not worry too much - I just didn't want to encourage direct `Context` usage.

**Comment by metaphore** [comment]
Oh, how could I missed that `Context` class, thanks for the details!

I will see into it, maybe I will come with some ideas.

**Comment by metaphore** [comment]
Hm, one thing still looks unclear to me regarding `Context`. I use `ContextIntitializer` to initialize application and seems like the only place where `Context` is being created is `ContextIntitializer#initiate()` so it's no way to get it directly from here, right? OK, but we still can obtain it by declaring `@Inject Context context` field and then hold the reference. But the problem is `Context` will be already cleared and completely empty at that moment, because of `Context#clear` is `true` by default and `ContextInitializer` gives no access to that property. And since we have `ContextInitializer#createMissingDependencies` which reflects exact `Context`'s field, maybe it will be reasonable to have same behavior for `Context#clear`?

And of course ability to obtain `Context` instance from `ContextIntitializer` after it been initiated would be very useful (at least for me). Let me put my usecase in here. I use `ApplicationListener` as a singleton for whole application and thus some parts of the system can ask it for some global things like `Context` in that way. Code of `ContextIntitializer` executes right from here and it would be correct to set context property here as well.

**Comment by czyzby** [comment]
`@Initiate` methods are executed before `Context` is cleared, so it is reasonable to create a configuration component and set up your `Context` there. Although I agree that its methods should be exposed. I'll look into `Context` and `ContextInitializer` API before the next release.

**Comment by czyzby** [comment]
This is resolved in `1.8` branch. Now to can remove event/message listeners and access `Context` during initiation.

**Comment by metaphore** [comment]
Looks great, thanks!

BTW, when do you plan to release 1.8?

**Comment by czyzby** [comment]
I'm just about to add `HighlightTextArea` support to `gdx-lml-vis` and I'm done, basically. I found some minor issues with `BusyBar` widget in VisUI, but I don't think it's worth it to wait until the next VisUI release to upload `1.8`. I'll probably upload it today or tomorrow. I'd appreciate if you run your project against current snapshot (`1.8.1.9.4-SNAPSHOT`) and check if everything's OK.

**Comment by metaphore** [comment]
I revisited my options on how to use `Context` to keep it alive after initialization and let me share few thoughts about it. First of all it's all fine and works brilliant, but I worry about `Context#components` footprint. I can see that after initialization it has about 50 components and near half of them are more like just service components for initialization needs (eg annotation scanners). I'm still not sure if there will be any significant difference if I somehow could clear `Context` from some components manually, but anyway it may be reasonable to provide method to remove specific components from it.

I'm not yet investigated on what exact components may be cut here, but just want to know your opinion if there is anything heavy that worth to be removed if I'm going to not clear context after initialization?

**Comment by czyzby** [comment]
You realize that modern JVMs can manage millions of objects without any problems, right? Even if you run into memory issues on mobile platforms, Autumn is unlikely to be the source of your problems. Most annotation processors are stateless or just keep their meta-data during the initiation. It was not the footprint I was worried about when making `Context` API public: reflection usage was. It's best to just set up your application with some reflection and then just plain old Java to do the rest of the work. If you start spawning something like particles with Autumn reflection-based factory on each frame, this might have a significant effect on your application (especially on mobile platforms).

**Comment by metaphore** [comment]
Yeah, it's pretty clear to me, but approach you chose for `Context` lifecycle (clear all components references so unnecessary part of them being garbage collected after initialization) made me ask you to be sure.

Will try snapshot right away and let you know if there is anything wrong.

**Comment by czyzby** [comment]
@metaphore `1.8.1.9.4` was released, it should be available soon.
