### ISSUE TITLE
LmlView without Stage

### ISSUE THREAD

**Issue by jojorabbit** [czyzby/gdx-lml#52]
Hi,
I would like to know if there is a way to have LmlView without stage. I know LmlView interface has method getStage(), What am trying to achieve is have all ui in lml and have game screen without stage just normally drawing sprites using batch. Is there easy way todo it?

I am aware that there is LmlApplicationListener(Game) and AbstractLmlView(Screen) that can be used but AbstractLmlView has stage and LmlView interface defines getStage method.
So i was thinking if i implement my own LmlView and method getStage returns null that could do the job. But i would like some better solution then returning null or returning empty stage.
The same goes for ViewController which implements LmlView again there is method getStage but that class belongs to Autumn MVC, i would like to avoid autumn for now.

Is there possibility that getStage method gets moved from LmlView to AbstractLmlView or StageLmlView?

Thanks.

Edit.
I found solution to my question so closing the issue.

**Comment by czyzby** [comment]
[This wiki page](https://github.com/czyzby/gdx-lml/wiki/Actor-injection) describes how you can access the parsed actors. I believe that [LmlParser methods](https://github.com/czyzby/gdx-lml/blob/master/lml/src/main/java/com/github/czyzby/lml/parser/LmlParser.java#L83-L113) creating views will accept pretty much anything and will inject the actors into a `Stage` only if `LmlView` interface is implemented - as you probably figured out by now.
