### ISSUE TITLE
Application crash on VisLml with Turkish locale

### ISSUE THREAD

**Issue by hedgecrab** [czyzby/gdx-lml#53]
#### Issue details
Application crashes completely if your Locale.getDefault() is Locale.forLanguageTag("tr");

#### Reproduction steps/code
https://garygregory.wordpress.com/2015/11/03/java-lowercase-conversion-turkey/

#### Version of LibGDX and/or relevant dependencies
Libgdx 1.9.4 + 

#### Stacktrace
```java
com.github.czyzby.lml.util.LmlParsingException: Error occurred during parsing near line 31 of the original file: "main-menu.lml".
REASON: Unable to parser alignment from raw data: right; no alignment value matching: right
	Due implementation of the parser, the real problematic line might SLIGHTLY vary from the given line number(s), but exception message should be clear enough to find the actual error.
	Currently parsed template part:
28 |VALID|             </vistable>
29 |VALID|         </vistable>
30 |VALID| 
31 |ERROR|         <vistable width="0.50%" height="1.00%" tablealign="right">
32 |     |             <myvistable id="main-coins-cont" onclick="main-coins-cont-click" visible="false" width="400" height="60" pad="10" tablealign="right">
33 |     |                 <visimage size="60" style="image-coin"/>
34 |     | 

```

#### Please select the affected platforms
- [*] Android
- [*] iOS (robovm)
- [*] iOS (MOE)
- [?] HTML/GWT
- [?] Windows
- [?] Linux
- [*] MacOS

**Comment by czyzby** [comment]
Interesting bug, I'll look into all `toLowerCase` calls before releasing LML for 1.9.6. Thanks.

**Comment by czyzby** [comment]
@hedgecrab Can you check if the issue persists in `1.9.1.9.6` version?

**Comment by hedgecrab** [comment]
@czyzby sure, I will try it tomorrow, thank you!

**Comment by hedgecrab** [comment]
@czyzby Seems like I'm not receiving any crashes after migration to gdx 1.9.6 + vislml 1.9.1.9.6, thank you so much

**Comment by czyzby** [comment]
Thanks for checking it out.
