### ISSUE TITLE
pls help me  the gwt websoket Thread is not supported

### ISSUE THREAD

**Issue by chongbo2013** [czyzby/gdx-lml#84]
pls help me  the gwt websoket Thread is not supported.
If I deal with the gdx drawing thread, it will cause blocking the drawing thread problem.

**Comment by chongbo2013** [comment]
If I am in the gdx drawing thread, to process the data of the websocket, it will cause blocking.

**Comment by chongbo2013** [comment]
yes. thank u very much.   can i add u  facebook

**Comment by czyzby** [comment]
I don't use Facebook, but I usually respond to new GitHub issues pretty quickly. ;) Feel free to close this one if the problem is resolved.

**Comment by chongbo2013** [comment]
thank u
