### ISSUE TITLE
websocket with GWT

### ISSUE THREAD

**Issue by sbalbach** [czyzby/gdx-lml#86]
I cannot get websockets to work with GWT.  If I use your gdx-setup and select desktop and gwt under Platforms, LibGDX Utils and WebSocket under Third-party, WebSocket Basic under Templates, the desktop application works fine.  However, the GWT compile has two errors in uiskin.json.  If I ignore those and zip up the gwt project's war directory into a war file and drop it into my Tomcat's webapps directory, Tomcat says that it deploys it but when I try to hit the URL, I get a 404.  Is there a special URL that I need to use to hit the app?

**Comment by czyzby** [comment]
It seems like there are a couple of problems with your application. Try solving them one by one.

You're saying there are some issues with the UI skin -  can you compile it without the web socket module? Also, there are some projects using GWT web sockets in the examples section, they might prove useful.

**Comment by sbalbach** [comment]
I have two questions, and a lot of text.  :)

I wouldn't call it "my application" at this point because all I did was take the generated code from your libGDX setup and compile it with GWT.  I haven't changed any of the code.  I expected the generated code to run cleanly.  Is that expectation wrong?

I had also previously tried to take a project that was created with the standard libGDX setup and added websockets to it manually.  Again, I got the desktop application working fine but when I hit the GWT application's URL in the browser I got a "Web sockets are not initiated." error from line 31 of your WebSockets class.  I traced that back to the fact that the desktop application was calling CommonWebSockets.initiate() but the GWT application was not.  So, I tried putting that call in the core project.  The desktop application still worked but the GWT application now wouldn't compile because of the new dependencies.  I managed to get the required sources for CommonWebSockets and nv-websocket-client set up but then the GWT compile complained about all kinds of javax.net.xxx classes not having source (like javax.net.SocketFactory).  That's when I decided to try to use your libGDX setup since I figured that it would take care of setting everything up for me correctly.

How is the GWT project supposed to work without calling CommonWebSockets.initiate() ?

**Comment by sbalbach** [comment]
I just tried to GWT compile your gdx-websocket-serialization-compare example and got the below error:

   Invoking Linker Cross-Site-Iframe
      [ERROR] The Cross-Site-Iframe linker does not support <script> tags in the gwt.xml files, but the gwt.xml file (or the gwt.xml files which it includes) contains the following script tags: 
soundmanager2-setup.js
soundmanager2-jsmin.js
In order for your application to run correctly, you will need to include these tags in your host page directly. In order to avoid this error, you will need to remove the script tags from the gwt.xml file, or add this property to the gwt.xml file: <set-configuration-property name='xsiframe.failIfScriptTag' value='FALSE'/>

Again, desktop version works as expected.

**Comment by czyzby** [comment]
[This is how you should initiate web sockets in GWT:](https://github.com/czyzby/gdx-lml/blob/master/examples/gdx-lml-vis-websocket/html/src/com/github/czyzby/client/HtmlLauncher.java#L17)

```java
    @Override
    public ApplicationListener createApplicationListener() {
        GwtWebSockets.initiate();
        return new Core();
}
```

[See the README file](https://github.com/czyzby/gdx-lml/tree/master/websocket/natives/gwt) of the GWT web sockets module.


As for the snippet you posted, I think the error message is quite clear:

> In order to avoid this error, you will need to remove the script tags from the gwt.xml file, or add this property to the gwt.xml file: set-configuration-property name='xsiframe.failIfScriptTag' value='FALSE'/

Try setting this property and compiling the project again.

> I'm using GWT 2.8.1; should I be using an older version maybe?

You should use the version that the LibGDX was compiled against. You can check LibGDX GWT module dependencies to make sure you're using the right one.

**Comment by sbalbach** [comment]
Firstly, thanks for your quick responses.

The GwtWebSockets.initiate() line was what I needed to fix my original libGDX code where I manually added websockets.

I still don't know why the example code and the code generated by your setup doesn't run but that's not really for me to track down (the example gwt.xml file already had the property that the error said to add).

I may drop libGDX completely and just write everything in javascript.  I don't need the desktop but libGDX provides a lot of plumbing but I believe I can write all of that myself.  We'll see.

**Comment by czyzby** [comment]
To be honest - if you mostly want to target the web, a JS framework might be a better choice. I've had good experiences with Phaser. I believe there are Kotlin and TypeScript bindings for it, if you prefer a statically typed language.

Should I close this issue?

**Comment by sbalbach** [comment]
sure, go ahead and close it
