### ISSUE TITLE
Ho to Use WebSocket?

### ISSUE THREAD

**Issue by Tuxerito** [czyzby/gdx-lml#91]
Hi.

I am trying to use this library but I don't know how to use it. I am new in LibGDX and WebSockets.

I want to connect to a server in LibGDX(HTML , Desktop and Android).

I have an HTML page where I have some JavaScript code where I can connect to the server with this code(similar)

```
const serverSocket = io(`https://hereistheurlserver.com?argument=value`);
serverSocket .on('event', (eventData) => {
//Here is the code to handle this event
});
```

That page works and I can connect and receive message from the server.

Now my question is how can I implement the same using this library?

I saw some of the samples but I don't understand how to use/configure to connect to the server.
How can I configure the connection? the sample said some like this
socket = ExtendedNet.getNet().newWebSocket("localhost", 8000);
In my case if the URL is under HTTPS do I need to use the port 442? do I need to use newSecureWebSocket()?

How can I pass the arguments?

I tested another library(IO.Socket) and I was able to connect to the server and also got events whit some like this;
```
Socket socket;
Options options = new Options();
options.query = "argument=value";

socket = IO.socket("https://hereistheurlserver.com", options);
socket.on("event", new EventListener(eventBus));
socket.connect();
```
-----------------------------

But that only works on Destktop not in HTML

I tried with this library but I got a connection time out(In Desktop and HTML), also I don't know how to pass the arguments and what port to use XD I change only the URL and the port from the sample code and also testing with newSecureWebSocket

Or is not possible to do the same like with the IO.Socket library and this library is for other things?

Thanks

**Comment by czyzby** [comment]
I think [someone had a similar problem](https://www.badlogicgames.com/forum/viewtopic.php?t=27274).

GWT does not support `IO.Socket`, as you've noticed. This library is a barebones web socket client implementation. To be honest, I haven't used `Socket.IO` myself, but if it adds anything on top of regular web sockets protocol, I'm pretty sure this library would be incompatible. `Socket.IO` should have a native JS client, so you can try to use that via GWT native calls. [Here's an example](https://github.com/czyzby/gdx-lml/blob/master/websocket/natives/gwt/src/main/java/com/github/czyzby/websocket/impl/GwtWebSocket.java) of blending native JS and GWT-compiled Java.

Or you could build your web socket server with Java/Kotlin/any other JVM language. You could try sharing some common logic between your client and server if you decide to switch. I recommend looking into [Vert.x](https://vertx.io/).

**Comment by Tuxerito** [comment]
Hi thanks for the reply.

So gdx-websocket is not for I want it? To connect to a server like the JavaScript or IO.Socket(Java) samples.

The server is not mine.

Thanks

**Comment by czyzby** [comment]
`gdx-websocket` lets you connect with any web socket server, but I don't think it supports whatever protocol `Socket.IO` adds on top of that. Instead, I recommend using `IO.Socket` for desktop/mobile and native JS client on GWT/HTML.

**Comment by Tuxerito** [comment]
Thanks again. 
I will check what you mentioned ☺
