### ISSUE TITLE
List of lml tags

### ISSUE THREAD

**Issue by Hellgasm** [czyzby/gdx-lml#92]
Hello,

Where can I find the list of all lml tags(or scene2d objects), all their attributes and possible attribute values?
There seems to be tags/attributes in your DTD file. How did you generate it? I couldn't even find Scene2d object and property list anywhere. Plus attribute descriptions would even be better but I don't think that's possible.

**Comment by czyzby** [comment]
The list of tags and attributes varies based on your LML parser setup. You can add and remove any tags or attributes to suit your application. The official DTD file contains only the default settings.

As for the DTD generation, check out [the official LML tutorial](https://github.com/czyzby/gdx-lml/wiki/Your-first-LML-application). In particular, the [content assist section](https://github.com/czyzby/gdx-lml/wiki/Your-first-LML-application#actual-content-assist) covers this topic.

**Comment by czyzby** [comment]
> I couldn't even find Scene2d object and property list anywhere.

The parser does not keep the tags and attributes lists directly. Instead, they are stored in the [`LmlSyntax`](https://github.com/czyzby/gdx-lml/blob/master/lml/src/main/java/com/github/czyzby/lml/parser/LmlSyntax.java) object, which the parser has a reference to.
