### ISSUE TITLE
Malformed snapshot JAR

### ISSUE THREAD

**Issue by metaphore** [czyzby/gdx-lml#97]
Hey @czyzby,
Sorry to bother you again with that nasty problem, but it seems that the latest published snapshot jar `gdx-lml-1.9.1.9.10-20190822.134652-9.jar` is somehow malformed and weights only a few bites. Compare it to some other old ones - https://oss.sonatype.org/content/repositories/snapshots/com/github/czyzby/gdx-lml/1.9.1.9.10-SNAPSHOT/

**Comment by metaphore** [comment]
All good with maven now, thanks!

Hm, I didn't have the same problem in my fork. When I run `:installAll` I can see that all the modules get assembled correct. 
I remember the project wasn't configured with Gradle wrapper. Do you use system installed Gradle?

**Comment by czyzby** [comment]
No, I used the wrapper. Can you check if zip archive in `build/distributions` has duplicate entries?

**Comment by metaphore** [comment]
Sorry, I'm not sure where to look for that dir, I don't have it anywhere in the project after clean build.

**Comment by czyzby** [comment]
@metaphore Run `./gradlew build distZip`, check `build/distributions` in the project root folder.

**Comment by czyzby** [comment]
I'm going to close this for now and write a small script to upload the archives separately. I'd appreciate if you checked the distribution archives @metaphore as described in the previous comment.

**Comment by metaphore** [comment]
@czyzby very sorry about a late response, checked it in the first place and completely forgot to leave a message. 
And yes, you're right, I can see the duplicated entries in the archive:
![image](https://user-images.githubusercontent.com/6159734/68385858-cfc5b780-01ae-11ea-97bc-5ab6c58a6e3e.png)

Not sure what causes this issue, maybe need to play with Gradle configuration to see when it happens.

**Comment by czyzby** [comment]
It's OK, thanks for the confirmation. The fastest fix would probably be to
